config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#home'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :appointments, only: [:create, :destroy, :edit, :update]
  resources :comments,     only: :create
end

app/models/application_record.rb
# Application record
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def end_after_start?
    return if [start_time.blank?, end_time.blank?].any?
    errors.add(:end_time, 'must be after start time') if start_time >= end_time
  end
end

app/models/appointment.rb
# Appointment model
class Appointment < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  default_scope -> { order(:start_time) }
  validates :user_id, presence: true
  validates :description, presence: true, length: { maximum: 80 }
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate  :end_after_start?

  def comment_feed
    Comment.where('appointment_id = ?', id)
  end
end

app/models/comment.rb
# Comment model
class Comment < ApplicationRecord
  belongs_to :appointment
  default_scope -> { order(:created_at) }
  validates :appointment_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates :author, presence: true
end

app/models/user.rb
# User model
class User < ApplicationRecord
  has_many :appointments, dependent: :destroy

  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def feed
    Appointment.all
  end

  private

  # Converts email to all lower-case.
  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
# Application controller
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private

  # Before filters

  # Confirms a logged-in user.
  def logged_in_user
    return if logged_in?
    store_location
    flash[:danger] = 'Please log in.'
    redirect_to login_url
  end
end

app/controllers/appointments_controller.rb
# Appointments controller
class AppointmentsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :edit, :update]
  before_action :correct_user,   only: [:destroy, :edit, :update]

  def create
    @appointment = current_user.appointments.build(appointment_params)
    if @appointment.save
      flash[:success] = 'Appointment created!'
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @appointment.destroy
    flash[:success] = 'Appointment deleted'
    redirect_to root_url
  end

  def edit
  end

  def update
    if @appointment.update_attributes(appointment_params)
      flash[:success] = 'Appointment updated'
      redirect_to root_url
    else
      render 'edit'
    end
  end

  private

  def appointment_params
    params.require(:appointment).permit(:description, :start_time, :end_time)
  end

  def correct_user
    @appointment = current_user.appointments.find_by(id: params[:id])
    redirect_to root_url if @appointment.nil?
  end
end

app/controllers/comments_controller.rb
# Comments controller
class CommentsController < ApplicationController
  before_action :logged_in_user, only: :create

  def create
    @appointment = Appointment.find(params[:comment][:id])
    @comment = @appointment.comments.build(comment_params)
    @comment.author = current_user.id
    if @comment.save
      redirect_to root_url
    else
      @comment_feed_items = []
      render 'static_pages/home'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :author, :appointment_id)
  end
end

app/controllers/sessions_controller.rb
# Sessions controller
class SessionsController < ApplicationController
  before_action :fetch_user, only: :create

  def new
  end

  def create
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      redirect_back_or root_url
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

  private

  def fetch_user
    @user = User.find_by(email: params[:session][:email].downcase)
  end
end

app/controllers/static_pages_controller.rb
# Static pages controller
class StaticPagesController < ApplicationController
  def home
    return unless logged_in?
    @appointment = current_user.appointments.build
    @feed_items = current_user.feed.paginate(page: params[:page], per_page: 20)
  end
end

app/controllers/users_controller.rb
# Users controller
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:update, :destroy]
  before_action :correct_user,   only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'InTime account created!'
      redirect_to root_url
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  # Before filters

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
# Application helper
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = 'InTime Appointment Management App'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/appointments_helper.rb
# Appointments helper
module AppointmentsHelper
end

app/helpers/comments_helper.rb
# Comments helper
module CommentsHelper
end

app/helpers/sessions_helper.rb
# Sessions helper
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  def current_user
    # if the session has a user id (someone is logged in), set
    # the instance variable @current_user to equal the user with that id
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
# Static pages helper
module StaticPagesHelper
  def alert_message
    messages = create_messages
    combined = ''
    messages.each do |k|
      combined += k + '_'
    end
    @message = combined
  end

  private

  def create_messages
    appts = fetch_appts
    now = Time.now
    messages = []
    appts.each do |j|
      start = j.start_time.to_time
      if now <= start && now > start - 1.hours
        messages << build_message(j.description, start, now)
      end
    end
    messages
  end

  def fetch_appts
    appts = []
    current_user.appointments.each do |i|
      appts << i
    end
    appts.pop
    appts
  end

  def build_message(desc, start, now)
    'Your appointment, ' + desc + ', is in ' +
      distance_of_time_in_words(start - now) + '.'
  end
end

app/helpers/users_helper.rb
# Users helper
module UsersHelper
end

app/views/appointments/_appointment.html.erb
<li id="appointment-<%= appointment.id %>">
  
  <span class="description">
    <% d = appointment.user.name + " | " + appointment.description %>
    <% s = appointment.start_time %>
    <% e = appointment.end_time %>
    <% t = Time.now %>
    <% if t > s && t < e %>
    <% d += ' - IN PROGRESS' %>
    <% end %>
    <% if t > e %>
    <% d += ' - PAST' %>
    <% end %>
    <%= d %>
  </span>
  
  <span class="details">
    <span class="detail-items">
      Starts: <%= appointment.start_time.strftime("%A, %B %d, %Y at %l:%M%p") %>
    </span>
    <span class="detail-items">
      Ends: <%= appointment.end_time.strftime("%A, %B %d, %Y at %l:%M%p") %>
    </span>
  </span>
  
  <span class="comments">
    <% @comment = appointment.comments.build %>
    <% @comment_feed_items = appointment.comment_feed %>
    <%= render 'shared/comment_feed' %>
    <%= form_for(@comment, html: { multipart: true }) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.hidden_field :id, value: appointment.id %>
      <%= f.text_field :content, placeholder: " Write a comment...", class: "comment-input" %>
      <%= f.submit "Post comment", class: "btn btn-primary comment-btn" %>
    <% end %>
  </span>
  
  <span>
    <% if current_user?(appointment.user) %>
      <%= link_to "edit appointment", edit_appointment_path(appointment) %> | 
      <%= link_to "delete appointment", appointment, method: :delete,
                                         data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/appointments/edit.html.erb
<% provide(:title, "Edit appointment") %>
<h3>Edit appointment</h3>
<%= render 'shared/appointment_form' %>

app/views/comments/_comment.html.erb
<li class="comment" id="comment-<%= comment.id %>">
  <span>
    <%= comment.content + " - " + User.find(comment.author).name %>
  </span>
</li>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to image_tag("intouch_logo.png", alt: "in touch logo"),
              root_path, id: "logo" %>
    <nav id="login-logout">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <%= link_to "Log out", logout_path, method: "delete" %>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all',
                            'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%#= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_appointment_form.html.erb
<%= form_for(@appointment, html: { multipart: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.label :description, "Description:" %>
    <%= f.text_field :description %>
    
    <%= f.label :start_time, "Starts:" %>
    <%= f.datetime_field :start_time %>
    
    <%= f.label :end_time, "Ends:" %>
    <%= f.datetime_field :end_time %>

  </div>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/shared/_comment_feed.html.erb
<% if @comment_feed_items.any? %>
  <ol class="appointments">
    <%= render @comment_feed_items %>
  </ol>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <%= will_paginate @feed_items %>
  <ol class="appointments">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <h1><%= current_user.name %></h1>
      </section>
      <section class="appointment_form">
        <h3>Create an appointment</h3>
        <%= render 'shared/appointment_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Appointments</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
  <script type="text/javascript">
    var messages = '<%=escape_javascript alert_message %>';
    if (messages != '') {
      var formattedMessages = messages.replace(new RegExp('_', 'g'), '\n');
      alert(formattedMessages);
    }
    setTimeout(function(){
      window.location.reload(1);
    }, 5 * 60 * 1000);
  </script>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to InTime</h1>
    <h2>
      Appointment Management for InTouch Health
    </h2>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>

  <%= link_to image_tag("intouch_logo.png", alt: "in touch logo"),
              'http://www.intouchhealth.com/' %>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirm password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>